### ISSUE TITLE
How can I adding Package "QuarternionFourierTransform" from *.jl?

### ISSUE THREAD

**Issue by bemoregt** [peakbook/QuaternionFourierTransform.jl#6]
Hi, @adamnemecek @peakbook 

How can I add your 3rd party  Package, "QuarternionFourierTransform" from *.jl?

I copy the *.jl file in julia directory & import Pkg; Pkg.add("QuaternionFourierTransform")

but it failed.

Error Message:

julia> import Pkg; Pkg.add("QuaternionFourierTransform")
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * QuaternionFourierTransform (not found in project, manifest or registry)
Please specify by known `name=uuid`.

----------------------------------------

It's so hard  to me(novice).

Thanks.

**Comment by peakbook** [comment]
Hi @bemoregt .
To add a package, use the add command in Julia REPL mode.
> (v1.1) pkg> add https://github.com/peakbook/Quaternions.jl
> (v1.1) pkg> add https://github.com/peakbook/QuaternionFourierTransform.jl

Please refer to [the official document](https://docs.julialang.org/en/v1/stdlib/Pkg/).

**Comment by bemoregt** [comment]
HI, @peakbook @adamnemecek.

OK, It works.

Thanks a lot.
