### ISSUE TITLE
I met this error when run main() in ex.jl .

### ISSUE THREAD

**Issue by bemoregt** [peakbook/QuaternionFourierTransform.jl#7]
Hi, @adamnemecek @peakbook 

I met this error when run main() in ex.jl .

julia> main()
[ Info: Recompiling stale cache file /Users/mun/.julia/compiled/v1.1/QuartzImageIO/n8vDP.ji for QuartzImageIO [dca85d43-d64c-5e67-8c65-017450d5d020]
┌ Warning: QuartzImageIO: Mapping to the storage type failed.
│ Perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ QuartzImageIO ~/.julia/packages/QuartzImageIO/9DhKg/src/QuartzImageIO.jl:227
┌ Warning: QuartzImageIO: Mapping to the storage type failed.
│ Perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ QuartzImageIO ~/.julia/packages/QuartzImageIO/9DhKg/src/QuartzImageIO.jl:227
┌ Warning: QuartzImageIO: Mapping to the storage type failed.
│ Perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ QuartzImageIO ~/.julia/packages/QuartzImageIO/9DhKg/src/QuartzImageIO.jl:227
┌ Warning: QuartzImageIO: Mapping to the storage type failed.
│ Perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ QuartzImageIO ~/.julia/packages/QuartzImageIO/9DhKg/src/QuartzImageIO.jl:227
84

What's wrong to me ?

My Env: MacOSX Mojave, Julia 1.1, and ...
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [5ae59095] Colors v0.9.5
  [7a1cc6ca] FFTW v0.2.4
  [5789e2e9] FileIO v1.0.5
  [587475ba] Flux v0.8.1
  [86fae568] ImageView v0.8.2
  [916415d5] Images v0.17.3
  [91a5bcdd] Plots v0.23.2
  [dca85d43] QuartzImageIO v0.5.2
  [4e470f00] QuaternionFourierTransform v0.0.0 #master (https://github.com/peakbook/QuaternionFourierTransform.jl)
  [94ee1d12] Quaternions v0.3.1+ #master (https://github.com/peakbook/Quaternions.jl)
  [5e47fb64] TestImages v0.4.1

Thanks.

**Comment by peakbook** [comment]
@bemoregt I fixed the program, please try again.

**Comment by bemoregt** [comment]
Thank you, @peakbook .

That's Great ~!
